require('mason-tool-installer').setup {
  ensure_installed = {
    -- rust
    "bash-language-server",
    "black",
    "clangd",
    "codelldb",
    "css-lsp",
    "debugpy",
    "emmet-ls",
    "flake8",
    "google-java-format",
    "gopls",
    "groovy-language-server",
    "html-lsp",
    "java-debug-adapter",
    "java-test",
    "jdtls",
    "json-lsp",
    "lemminx",
    "lua-language-server",
    "perlnavigator",
    "prettier",
    "pyright",
    "rust-analyzer",
    "rustfmt",
    "stylua",
    "tailwindcss-language-server",
    "typescript-language-server",
    "vim-language-server",
    "yaml-language-server",
  },
  auto_update = false,
  run_on_start = true,
  start_delay = 3000,
  debounce_hours = 5,
}
