require("user.lsp.languages.rust")
require("user.lsp.languages.lua")
require("user.lsp.languages.python")
require("user.lsp.languages.java")
require("user.lsp.languages.clang")
require("user.lsp.languages.typst")
require("user.lsp.languages.markdown")
require("user.lsp.languages.shell")
-- require("user.lsp.languages.go")
-- require("user.lsp.languages.yaml")
